In [2]:
# Name : Abubakar
# Task: 1 (Week 1 AICP)
import numpy as np

# NumPy array of even integers from 30 to 70
# np.arange(start, stop, step) generates an array of evenly spaced values within a given interval
array = np.arange(30, 71, 2)

# Printing the array
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [6]:
# Name : Abubakar
# Task : 2(Week 1 AICP)
import numpy as np

# Generating an array of 15 random numbers from a standard normal distribution
random_array = np.random.randn(15)

# Printing the array
print(random_array)

[-0.65797605  0.65445601  0.36877421  1.90066539  1.74911071  1.28409399
  0.03996813 -1.0620545   0.78762508  1.68835149  0.18924977  0.47183194
 -1.21638566  1.48788422 -0.53572434]


In [8]:
# Name : Abubakar 
# Task : 3(Week 1 AICP)
import numpy as np

#Initiallizing Matrices
matrix_a = np.array([[3, 1, 2], [5, 1, 3]])
matrix_b = np.array([[6, 2, 10], [7, 4, 8]])

# np.cross(first matrix, Second Matric) function for cross-product of matrices
cross_product = np.cross(matrix_a, matrix_b)
print(cross_product)

[[  6 -18   0]
 [ -4 -19  13]]


In [11]:
# Name : Abubakar
# Task : 4(Week 1 AICP)
import numpy as np

# Defining a square matrix
matrix = np.array([[3, 5, 2],
                   [2, 4, 3],
                   [5, 7, 6]])

# Calculating the determinant using inalg.det(matrix) function
determinant = np.linalg.det(matrix)

# Printing the determinant
print("Determinant of the matrix is:", determinant)

Determinant of the matrix is: 11.999999999999995


In [14]:
# Name : Abubakar
# Task : 5(Week 1 AICP)
import numpy as np

# Generating the 3x3x3 array with random values between 0 and 10
array = np.random.rand(3, 3, 3)*10

# Printing the array
print("3x3x3 array with random values:")
print(array)

3x3x3 array with random values:
[[[3.62062802 5.52507931 1.08733516]
  [8.56246676 4.6708688  0.24619908]
  [0.39313616 9.2215649  1.47315501]]

 [[7.08617827 9.20258565 2.91064172]
  [7.51963856 1.36843979 0.1534583 ]
  [7.90480329 0.0522571  2.75947922]]

 [[1.23529555 4.95452988 1.53085441]
  [5.84247643 4.48405127 6.20714498]
  [5.90854022 6.92184095 1.76379974]]]


In [15]:
# Name : Abubakar 
# Task : 6(Week 1 AIPCP)
import numpy as np

# Creating a 5x5 array with random values between 0 and 100
array = np.random.randint(0, 101, size=(5, 5))

# Finding the minimum and maximum values
min_value = np.min(array)
max_value = np.max(array)

# Printing the results
print("5x5 array with random values:")
print(array)
print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")


5x5 array with random values:
[[72 26 88 20 15]
 [55 59 50 57 30]
 [86 97 23 76 94]
 [39 75 60 58 65]
 [33 81 62 60 63]]
Minimum value: 15
Maximum value: 97


In [17]:
# Name : Abubakar
# Task : 7(Week 1 AICP)
import numpy as np

# Create a sample array
array = np.random.randn(5, 10)  # 5 rows, 10 columns

# Calculate statistics along the second axis (columns)
mean = np.mean(array, axis=1)
std_deviation = np.std(array, axis=1)
variance = np.var(array, axis=1)

# Print the results
print("Mean:", mean)
print("Standard deviation:", std_deviation)
print("Variance:", variance)


Mean: [ 0.32847104 -0.10264509 -0.19476414  0.2294131  -0.13905973]
Standard deviation: [1.12040465 1.40300094 1.19670887 1.0011686  0.54463767]
Variance: [1.25530658 1.96841163 1.43211212 1.00233856 0.29663019]
